# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
osx_image: xcode9.2

os:
  - linux
  - osx

r:
  - oldrel
  - release
